# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /__w/asgard/asgard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /__w/asgard/asgard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /__w/asgard/asgard/CMakeFiles /__w/asgard/asgard/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /__w/asgard/asgard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f third_party/prometheus-cpp/CMakeFiles/gmock_main.dir/build.make third_party/prometheus-cpp/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named prometheus-cpp-core

# Build rule for target.
prometheus-cpp-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus-cpp-core
.PHONY : prometheus-cpp-core

# fast build rule for target.
prometheus-cpp-core/fast:
	$(MAKE) -f third_party/prometheus-cpp/core/CMakeFiles/prometheus-cpp-core.dir/build.make third_party/prometheus-cpp/core/CMakeFiles/prometheus-cpp-core.dir/build
.PHONY : prometheus-cpp-core/fast

#=============================================================================
# Target rules for targets named prometheus-cpp-pull

# Build rule for target.
prometheus-cpp-pull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus-cpp-pull
.PHONY : prometheus-cpp-pull

# fast build rule for target.
prometheus-cpp-pull/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/prometheus-cpp-pull.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/prometheus-cpp-pull.dir/build
.PHONY : prometheus-cpp-pull/fast

#=============================================================================
# Target rules for targets named civetweb

# Build rule for target.
civetweb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 civetweb
.PHONY : civetweb

# fast build rule for target.
civetweb/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build
.PHONY : civetweb/fast

#=============================================================================
# Target rules for targets named asgard

# Build rule for target.
asgard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asgard
.PHONY : asgard

# fast build rule for target.
asgard/fast:
	$(MAKE) -f asgard/CMakeFiles/asgard.dir/build.make asgard/CMakeFiles/asgard.dir/build
.PHONY : asgard/fast

#=============================================================================
# Target rules for targets named libasgard

# Build rule for target.
libasgard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libasgard
.PHONY : libasgard

# fast build rule for target.
libasgard/fast:
	$(MAKE) -f asgard/CMakeFiles/libasgard.dir/build.make asgard/CMakeFiles/libasgard.dir/build
.PHONY : libasgard/fast

#=============================================================================
# Target rules for targets named benchmark_projector_cache

# Build rule for target.
benchmark_projector_cache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_projector_cache
.PHONY : benchmark_projector_cache

# fast build rule for target.
benchmark_projector_cache/fast:
	$(MAKE) -f asgard/tests/CMakeFiles/benchmark_projector_cache.dir/build.make asgard/tests/CMakeFiles/benchmark_projector_cache.dir/build
.PHONY : benchmark_projector_cache/fast

#=============================================================================
# Target rules for targets named handler_test

# Build rule for target.
handler_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 handler_test
.PHONY : handler_test

# fast build rule for target.
handler_test/fast:
	$(MAKE) -f asgard/tests/CMakeFiles/handler_test.dir/build.make asgard/tests/CMakeFiles/handler_test.dir/build
.PHONY : handler_test/fast

#=============================================================================
# Target rules for targets named projector_test

# Build rule for target.
projector_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projector_test
.PHONY : projector_test

# fast build rule for target.
projector_test/fast:
	$(MAKE) -f asgard/tests/CMakeFiles/projector_test.dir/build.make asgard/tests/CMakeFiles/projector_test.dir/build
.PHONY : projector_test/fast

#=============================================================================
# Target rules for targets named util_test

# Build rule for target.
util_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util_test
.PHONY : util_test

# fast build rule for target.
util_test/fast:
	$(MAKE) -f asgard/tests/CMakeFiles/util_test.dir/build.make asgard/tests/CMakeFiles/util_test.dir/build
.PHONY : util_test/fast

#=============================================================================
# Target rules for targets named direct_path_response_builder_test

# Build rule for target.
direct_path_response_builder_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 direct_path_response_builder_test
.PHONY : direct_path_response_builder_test

# fast build rule for target.
direct_path_response_builder_test/fast:
	$(MAKE) -f asgard/tests/CMakeFiles/direct_path_response_builder_test.dir/build.make asgard/tests/CMakeFiles/direct_path_response_builder_test.dir/build
.PHONY : direct_path_response_builder_test/fast

asgard/config.o: asgard/config.cpp.o

.PHONY : asgard/config.o

# target to build an object file
asgard/config.cpp.o:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/asgard/config.cpp.o
.PHONY : asgard/config.cpp.o

asgard/config.i: asgard/config.cpp.i

.PHONY : asgard/config.i

# target to preprocess a source file
asgard/config.cpp.i:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/asgard/config.cpp.i
.PHONY : asgard/config.cpp.i

asgard/config.s: asgard/config.cpp.s

.PHONY : asgard/config.s

# target to generate assembly for a file
asgard/config.cpp.s:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/asgard/config.cpp.s
.PHONY : asgard/config.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... config"
	@echo "... gmock_main"
	@echo "... prometheus-cpp-core"
	@echo "... prometheus-cpp-pull"
	@echo "... civetweb"
	@echo "... asgard"
	@echo "... libasgard"
	@echo "... benchmark_projector_cache"
	@echo "... handler_test"
	@echo "... projector_test"
	@echo "... util_test"
	@echo "... direct_path_response_builder_test"
	@echo "... asgard/config.o"
	@echo "... asgard/config.i"
	@echo "... asgard/config.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

