name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - release

jobs:
    
    checks:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: checkout submodules
          shell: bash
          run: |
            docker run --rm --name asgard -d -v $(pwd):/src navitia/asgard-build-deps:latest sh -c 'while true; do sleep 10; done'
            sed -i 's,git\@github.com:\([^/]*\)/\(.*\).git,https://github.com/\1/\2,' .gitmodules
            git submodule update --init --recursive
    build:
        runs-on: ubuntu-latest
        container:
            image: navitia/asgard-build-deps:latest
        steps:
        - uses: actions/checkout@v2
        - name: build
          run: |
            echo `ls`
            scripts/check-formatting.sh
            mkdir build && cd build && cmake ../ && make && cd asgard && ctest
