name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - release

env:
  NAVITIA_VALHALLA_TAG: 3.1.4

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build asgard docker
      run:
        docker build --build-arg NAVITIA_VALHALLA_TAG=$NAVITIA_VALHALLA_TAG ./docker/asgard-app
    - name: dockerhub login
      run:
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: push image release
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/release' }}
      run:
        RELEASE_TAG=$(make get-app-release-tag)
        docker tag navitia/asgard-app navitia/asgard-app:RELEASE_TAG
        docker push navitia/asgard-app:RELEASE_TAG
    - name: push image master
      if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run:
        docker tag navitia/asgard-app navitia/asgard-app:master
        docker push navitia/asgard-app:master

  build:
    runs-on: ubuntu-latest
    container:
      image: navitia/asgard-build-deps:3.1.4
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: check formatting
      run: scripts/check-formatting.sh
    - name: create libvalhalla symlink
      run: ln -s /libvalhalla .
    - name: Run cmake
      run: mkdir build && cd build && cmake -DENABLE_SANITIZERS=On ../
    - name: build
      run: cd build && make
    - name: test
      run: cd asgard && ctest
