name: CI

on:
    pull_request:
    push:
        branches:
            - master
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: navitia/asgard-build-deps:latest
        
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: 'recursive'
        - name: build
          run: |
            scripts/check-formatting.sh
            pwd      
            mkdir build && cd build && cmake ../ && make && cd asgard && ctest
